name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json

  grant-revoke-tests:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_REFRESH_TOKEN: ${{ secrets.OUTREACH_REFRESH_TOKEN }}
      BATON_OUTREACH_CLIENT_ID: ${{ secrets.OUTREACH_CLIENT_ID }}
      BATON_OUTREACH_CLIENT_SECRET: ${{ secrets.OUTREACH_CLIENT_SECRET }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-outreach
        run: go build ./cmd/baton-outreach
      - name: Profile Grant/revoke test
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-outreach
          baton-entitlement: 'profile:41:assigned'
          baton-principal: '3'
          baton-principal-type: user
      - name: Team Grant/revoke test
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-outreach
          baton-entitlement: 'team:1:member'
          baton-principal: '3'
          baton-principal-type: user


  with-refresh-token-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      OUTREACH_REFRESH_TOKEN: ${{ secrets.OUTREACH_REFRESH_TOKEN }}
      OUTREACH_CLIENT_ID: ${{ secrets.OUTREACH_CLIENT_ID }}
      OUTREACH_CLIENT_SECRET: ${{ secrets.OUTREACH_CLIENT_SECRET }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-outreach
        run: go build ./cmd/baton-outreach
      - name: Test refresh token authentication
        env:
          CONNECTOR_FLAGS: >-
            --outreach-client-id='${{ env.OUTREACH_CLIENT_ID }}'
            --outreach-client-secret='${{ env.OUTREACH_CLIENT_SECRET }}'
            --refresh-token='${{ env.OUTREACH_REFRESH_TOKEN }}'
        run: ./baton-outreach ${{ env.CONNECTOR_FLAGS }}
