name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  grant-revoke-tests:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_REFRESH_TOKEN: ${{ secrets.OUTREACH_REFRESH_TOKEN }}
      BATON_OUTREACH_CLIENT_ID: ${{ secrets.OUTREACH_CLIENT_ID }}
      BATON_OUTREACH_CLIENT_SECRET: ${{ secrets.OUTREACH_CLIENT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-outreach
        run: go build ./cmd/baton-outreach
      - name: Profile Grant/revoke test
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-outreach
          baton-entitlement: "profile:41:assigned"
          baton-principal: "3"
          baton-principal-type: user
      - name: Team Grant/revoke test
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-outreach
          baton-entitlement: "team:1:member"
          baton-principal: "3"
          baton-principal-type: user
  refresh-token-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_REFRESH_TOKEN: ${{ secrets.OUTREACH_REFRESH_TOKEN }}
      BATON_OUTREACH_CLIENT_ID: ${{ secrets.OUTREACH_CLIENT_ID }}
      BATON_OUTREACH_CLIENT_SECRET: ${{ secrets.OUTREACH_CLIENT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-outreach
        run: go build ./cmd/baton-outreach
      - name: Test refresh token authentication
        run: ./baton-outreach
  action-tests:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_REFRESH_TOKEN: ${{ secrets.OUTREACH_REFRESH_TOKEN }}
      BATON_OUTREACH_CLIENT_ID: ${{ secrets.OUTREACH_CLIENT_ID }}
      BATON_OUTREACH_CLIENT_SECRET: ${{ secrets.OUTREACH_CLIENT_SECRET }}
      TEST_USER_ID: ${{ secrets.OUTREACH_TEST_USER_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-outreach
        run: go build ./cmd/baton-outreach
      - name: Test disable user action
        run: |
          ./baton-outreach \
            --invoke-action=disable_user \
            --invoke-action-args='{"user_id": "${{ env.TEST_USER_ID }}"}'
      - name: Test enable user action
        run: |
          ./baton-outreach \
            --invoke-action=enable_user \
            --invoke-action-args='{"user_id": "${{ env.TEST_USER_ID }}"}'
